spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/ProjectHope
    url: jdbc:postgresql://database-1.crc20wkc223a.eu-north-1.rds.amazonaws.com:5432/ProjectHope
    username: postgres
    password: mahesh$106
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
